version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.12"
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/devuser/.gitconfig:ro
      - ~/.ssh:/home/devuser/.ssh:ro
    networks:
      - dev-network
    environment:
      - PYTHONPATH=/workspace/src
      - VIRTUAL_ENV=/workspace/.venv
      - PATH=/workspace/.venv/bin:/usr/local/bin:/usr/bin:/bin
    command: sleep infinity
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=512m
      - /var/tmp:rw,noexec,nosuid,size=512m

  # Optional: Add database service
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network
    ports:
      - "5432:5432"

  # Optional: Add Redis service
  redis:
    image: redis:7-alpine
    networks:
      - dev-network
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  dev-network:
    driver: bridge
