version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.12"
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/devuser/.gitconfig:ro
      - ~/.ssh:/home/devuser/.ssh:ro
    networks:
      - dev-network
    environment:
      - PYTHONPATH=/workspace/src
      - VIRTUAL_ENV=/workspace/.venv
      - PATH=/home/devuser/.cargo/bin:/workspace/.venv/bin:/usr/local/bin:/usr/bin:/bin
    command: sleep infinity
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=512m
      - /var/tmp:rw,noexec,nosuid,size=512m

networks:
  dev-network:
    driver: bridge
